services:
  # Node.js Express application
  forum-backend:
    build: ./backend
    container_name: forum-backend
    restart: no
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "8080:3000"
    volumes:
      - forum-db:/data
    env_file:
      - .env

volumes:
  forum-db: